name: patient_care
description: A comprehensive health care management app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.65.0
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  http: ^1.1.0
  shared_preferences: ^2.2.0
  intl: ^0.18.1
  flutter_secure_storage: ^9.0.0
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.1
  google_fonts: ^6.1.0
  pull_to_refresh: ^2.0.0
  uuid: ^4.1.0
  sqflite_common_ffi: ^2.3.0
  logging: ^1.2.0
  logger: ^2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  # Remove the assets section since we're not using any images yet
